/**
 * ChatMize visitor support widget (embed script).
 *
 * Usage (generated by SupportChatView > Embed):
 *   <script src="https://app.chatmize.com/widget.js"
 *           data-workspace="ws-chatmize-hq"
 *           data-widget="support-chat-primary" async></script>
 *
 * Fully functional end to end:
 *  - loads the widget config publicly from the chatmize-prod Firestore database
 *  - renders launcher + chat panel in a shadow DOM (style-isolated)
 *  - enforces the widget's domain allowlist
 *  - pre-chat lead capture (name / email / phone, per widget config)
 *  - quick replies route into the widget's published BotMap flow (never dead)
 *  - visitor messages land in workspaces/{ws}/conversations/web_{sid}/messages
 *    so agents see them live in Live Conversations
 *  - listens in realtime for agent/bot replies; an agent reply pauses the bot
 *
 * Built by scripts/build-widget.mjs -> dist/widget.js (IIFE, minified).
 * No React, no build-time secrets. The Firebase web API key is public by design.
 */
import { initializeApp } from 'firebase/app';
import {
  getFirestore,
  doc,
  getDoc,
  setDoc,
  addDoc,
  collection,
  query,
  orderBy,
  onSnapshot,
  serverTimestamp,
} from 'firebase/firestore';
import { SupportBotSession, createSessionFromBotMap, BotQuickReply } from '../utils/supportBotRunner';

declare const CM_FIREBASE_API_KEY: string;
declare const CM_PROJECT_ID: string;

const DB_ID = 'chatmize-prod';
const CONVO_PREFIX = 'web_';

interface WidgetConfig {
  id: string;
  status: string;
  headline: string;
  subheadline: string;
  welcomeMessage: string;
  brandColor: string;
  position: 'bottom_right' | 'bottom_left';
  launcherIcon: string;
  launcherText: string;
  avatarUrl: string;
  botName: string;
  quickReplies: Array<{ id: string; label: string; payload: string }>;
  requireEmailCapture: boolean;
  requireNameCapture: boolean;
  requirePhoneCapture: boolean;
  removeBranding: boolean;
  autoOpenDelaySeconds: number;
  whitelistedDomains: string[];
  publishedFlow?: { nodes: any[]; connections: any[] } | null;
}

function el(tag: string, cls: string, html?: string): HTMLElement {
  const e = document.createElement(tag);
  e.className = cls;
  if (html !== undefined) e.innerHTML = html;
  return e;
}

function esc(s: string): string {
  return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function domainAllowed(whitelist: string[]): boolean {
  if (!whitelist || whitelist.length === 0) return true;
  const host = window.location.hostname.toLowerCase();
  return whitelist.some((raw) => {
    const rule = (raw || '').trim().toLowerCase();
    if (!rule) return false;
    if (rule === 'localhost' || rule === 'localhost:3000') return host === 'localhost' || host === '127.0.0.1';
    const bare = rule.replace(/^[a-z]+:\/\//, '').split('/')[0].split(':')[0];
    if (bare.startsWith('*.')) {
      const suffix = bare.slice(1); // ".example.com"
      return host === bare.slice(2) || host.endsWith(suffix);
    }
    return host === bare;
  });
}

function launcherIconSvg(kind: string): string {
  const common = 'width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
  if (kind === 'headset')
    return `<svg ${common}><path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3v5zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3v5z"/></svg>`;
  if (kind === 'sparkle')
    return `<svg ${common}><path d="M12 3l1.9 5.8L19.7 10.7l-5.8 1.9L12 18.4l-1.9-5.8L4.3 10.7l5.8-1.9L12 3z"/><path d="M19 3l.8 2.2L22 6l-2.2.8L19 9l-.8-2.2L16 6l2.2-.8L19 3z"/></svg>`;
  if (kind === 'bot')
    return `<svg ${common}><rect x="4" y="8" width="16" height="12" rx="2"/><path d="M12 8V4M8 4h8"/><circle cx="9" cy="13" r="1" fill="currentColor"/><circle cx="15" cy="13" r="1" fill="currentColor"/><path d="M9 17h6"/></svg>`;
  return `<svg ${common}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>`;
}

const CSS = `
.cm-launcher{position:fixed;z-index:2147483000;display:flex;align-items:center;gap:8px;border:none;cursor:pointer;
  padding:12px 18px;border-radius:999px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
  font-size:14px;font-weight:700;color:#0b1220;box-shadow:0 8px 28px rgba(0,0,0,.35);transition:transform .15s}
.cm-launcher:hover{transform:scale(1.05)}
.cm-panel{position:fixed;z-index:2147483001;width:378px;max-width:calc(100vw - 32px);height:540px;max-height:calc(100vh - 120px);
  display:flex;flex-direction:column;border-radius:18px;overflow:hidden;background:#0f172a;color:#e2e8f0;
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;box-shadow:0 24px 70px rgba(0,0,0,.5);
  border:1px solid rgba(255,255,255,.12);opacity:0;transform:translateY(16px) scale(.98);pointer-events:none;transition:all .22s ease}
.cm-panel.cm-open{opacity:1;transform:none;pointer-events:auto}
.cm-head{padding:14px;display:flex;align-items:center;gap:10px;color:#fff}
.cm-head img{width:38px;height:38px;border-radius:50%;object-fit:cover;border:2px solid rgba(255,255,255,.35)}
.cm-head .cm-title{font-size:13px;font-weight:700;line-height:1.25}
.cm-head .cm-sub{font-size:11px;opacity:.92;display:flex;align-items:center;gap:5px}
.cm-dot{width:7px;height:7px;border-radius:50%;background:#4ade80;box-shadow:0 0 6px #4ade80;animation:cm-pulse 2s infinite}
@keyframes cm-pulse{50%{opacity:.5}}
.cm-close{margin-left:auto;background:rgba(0,0,0,.2);border:none;color:#fff;border-radius:8px;width:28px;height:28px;cursor:pointer;font-size:14px}
.cm-subhead{padding:8px 14px;background:rgba(0,0,0,.35);font-size:11px;color:#94a3b8;border-bottom:1px solid rgba(255,255,255,.06)}
.cm-msgs{flex:1;overflow-y:auto;padding:14px;display:flex;flex-direction:column;gap:10px;background:rgba(0,0,0,.25)}
.cm-bubble{max-width:85%;padding:10px 13px;border-radius:16px;font-size:13.5px;line-height:1.45;word-wrap:break-word}
.cm-bot{background:#1e293b;border:1px solid rgba(255,255,255,.08);border-top-left-radius:4px;align-self:flex-start}
.cm-user{align-self:flex-end;color:#0b1220;font-weight:500;border-top-right-radius:4px}
.cm-time{font-size:9px;color:#64748b;margin-top:3px;padding:0 4px}
.cm-qr{display:flex;flex-wrap:wrap;gap:6px;padding:2px 0}
.cm-qr button{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.06);color:#7dd3fc;font-size:12px;font-weight:600;
  padding:7px 12px;border-radius:999px;cursor:pointer;transition:all .15s}
.cm-qr button:hover{background:rgba(255,255,255,.14)}
.cm-typing{display:flex;gap:5px;padding:12px 14px;background:#1e293b;border-radius:16px;border-top-left-radius:4px;align-self:flex-start;width:fit-content}
.cm-typing span{width:7px;height:7px;background:#7dd3fc;border-radius:50%;animation:cm-b 1.2s infinite}
.cm-typing span:nth-child(2){animation-delay:.15s}.cm-typing span:nth-child(3){animation-delay:.3s}
@keyframes cm-b{0%,60%,100%{transform:none;opacity:.5}30%{transform:translateY(-5px);opacity:1}}
.cm-lead{padding:14px;display:flex;flex-direction:column;gap:8px;background:rgba(0,0,0,.25)}
.cm-lead p{font-size:12px;color:#cbd5e1;margin:0 0 2px}
.cm-lead input{background:#020617;border:1px solid rgba(255,255,255,.12);border-radius:10px;padding:9px 12px;color:#fff;font-size:13px;width:100%;box-sizing:border-box}
.cm-lead input:focus{outline:none;border-color:#22d3ee}
.cm-lead button{border:none;border-radius:10px;padding:10px;font-weight:700;font-size:13px;cursor:pointer;color:#0b1220}
.cm-input{display:flex;gap:8px;padding:10px;border-top:1px solid rgba(255,255,255,.08);background:#0f172a}
.cm-input input{flex:1;background:#020617;border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:9px 12px;color:#fff;font-size:13px}
.cm-input input:focus{outline:none;border-color:#22d3ee}
.cm-send{width:38px;height:38px;border:none;border-radius:12px;cursor:pointer;color:#0b1220;font-weight:700;display:flex;align-items:center;justify-content:center;flex:none}
.cm-brand{padding:6px;text-align:center;font-size:10px;color:#475569;background:rgba(0,0,0,.35)}
.cm-brand a{color:#7dd3fc;text-decoration:none}
`;

async function boot() {
  const script = document.currentScript as HTMLScriptElement | null;
  const qs = (k: string) => script?.dataset?.[k] || new URLSearchParams(window.location.search).get(k) || '';
  const workspaceId = qs('workspace');
  const widgetId = qs('widget');
  if (!workspaceId || !widgetId) {
    console.warn('[ChatMize widget] missing data-workspace / data-widget on the embed script tag.');
    return;
  }

  const app = initializeApp({ apiKey: CM_FIREBASE_API_KEY, projectId: CM_PROJECT_ID });
  const db = getFirestore(app, DB_ID);

  let cfg: WidgetConfig;
  try {
    const snap = await getDoc(doc(db, 'workspaces', workspaceId, 'support_widgets', widgetId));
    if (!snap.exists()) {
      console.warn('[ChatMize widget] widget not found:', widgetId);
      return;
    }
    const d = snap.data() as Record<string, any>;
    cfg = {
      id: widgetId,
      status: d.status || 'active',
      headline: d.headline || 'How can we help?',
      subheadline: d.subheadline || '',
      welcomeMessage: d.welcomeMessage || 'Hi there! How can we help you today?',
      brandColor: d.brandColor || '#00d2ff',
      position: d.position === 'bottom_left' ? 'bottom_left' : 'bottom_right',
      launcherIcon: d.launcherIcon || 'chat',
      launcherText: d.launcherText || 'Chat with us',
      avatarUrl: d.avatarUrl || '',
      botName: d.botName || 'Support',
      quickReplies: Array.isArray(d.quickReplies) ? d.quickReplies : [],
      requireEmailCapture: !!d.requireEmailCapture,
      requireNameCapture: !!d.requireNameCapture,
      requirePhoneCapture: !!d.requirePhoneCapture,
      removeBranding: !!d.removeBranding,
      autoOpenDelaySeconds: Number(d.autoOpenDelaySeconds || 0),
      whitelistedDomains: Array.isArray(d.whitelistedDomains) ? d.whitelistedDomains : [],
      publishedFlow: d.publishedFlow || null,
    };
  } catch (e) {
    console.warn('[ChatMize widget] could not load widget config:', e);
    return;
  }

  if (cfg.status !== 'active') return;
  if (!domainAllowed(cfg.whitelistedDomains)) {
    console.warn('[ChatMize widget] this domain is not allowlisted for widget', widgetId);
    return;
  }

  // Note: visitor writes to the widget doc are denied by Firestore rules;
  // view stats are intentionally not counted client-side.

  const side = cfg.position === 'bottom_left' ? 'left' : 'right';
  const host = el('div', '');
  host.id = 'chatmize-widget-root';
  document.body.appendChild(host);
  const shadow = host.attachShadow({ mode: 'open' });
  const style = document.createElement('style');
  style.textContent = CSS;
  shadow.appendChild(style);

  // Launcher
  const launcher = el('button', 'cm-launcher') as HTMLButtonElement;
  launcher.style.background = cfg.brandColor;
  launcher.style[side] = '20px';
  launcher.style.bottom = '20px';
  launcher.innerHTML = `${launcherIconSvg(cfg.launcherIcon)}<span>${esc(cfg.launcherText)}</span>`;
  shadow.appendChild(launcher);

  // Panel
  const panel = el('div', 'cm-panel');
  panel.style[side] = '20px';
  panel.style.bottom = '84px';
  const avatarImg = cfg.avatarUrl
    ? `<img src="${esc(cfg.avatarUrl)}" alt="${esc(cfg.botName)}" onerror="this.style.display='none'"/>`
    : '';
  panel.innerHTML = `
    <div class="cm-head" style="background:${esc(cfg.brandColor)}">
      ${avatarImg}
      <div>
        <div class="cm-title">${esc(cfg.headline)}</div>
        <div class="cm-sub"><span class="cm-dot"></span><span>${esc(cfg.botName)} &middot; typically replies instantly</span></div>
      </div>
      <button class="cm-close" aria-label="Close chat">&times;</button>
    </div>
    ${cfg.subheadline ? `<div class="cm-subhead">${esc(cfg.subheadline)}</div>` : ''}
    <div class="cm-msgs"></div>
    <div class="cm-lead" style="display:none"></div>
    <div class="cm-input">
      <input type="text" placeholder="Type your message..." aria-label="Type your message"/>
      <button class="cm-send" style="background:${esc(cfg.brandColor)}" aria-label="Send">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M22 2L11 13"/><path d="M22 2l-7 20-4-9-9-4 20-7z"/></svg>
      </button>
    </div>
    ${cfg.removeBranding ? '' : `<div class="cm-brand">Powered by <a href="https://chatmize.com" target="_blank" rel="noopener">ChatMize</a></div>`}
  `;
  shadow.appendChild(panel);

  const msgsEl = panel.querySelector('.cm-msgs') as HTMLElement;
  const leadEl = panel.querySelector('.cm-lead') as HTMLElement;
  const inputEl = panel.querySelector('.cm-input input') as HTMLInputElement;
  const sendBtn = panel.querySelector('.cm-send') as HTMLButtonElement;
  const closeBtn = panel.querySelector('.cm-close') as HTMLButtonElement;
  const inputBar = panel.querySelector('.cm-input') as HTMLElement;

  const scrollDown = () => { msgsEl.scrollTop = msgsEl.scrollHeight; };
  const now = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  function addMsg(text: string, who: 'bot' | 'user') {
    const wrap = el('div', '');
    const b = el('div', `cm-bubble ${who === 'bot' ? 'cm-bot' : 'cm-user'}`);
    if (who === 'user') b.style.background = cfg.brandColor;
    b.textContent = text;
    const t = el('div', 'cm-time', who === 'bot' ? `${esc(cfg.botName)} &middot; ${now()}` : now());
    if (who === 'user') t.style.textAlign = 'right';
    wrap.appendChild(b); wrap.appendChild(t);
    msgsEl.appendChild(wrap); scrollDown();
  }

  function addQuickReplies(replies: BotQuickReply[], onPick: (r: BotQuickReply) => void) {
    if (!replies.length) return;
    const row = el('div', 'cm-qr');
    replies.forEach((r) => {
      const btn = el('button', '', esc(r.label)) as HTMLButtonElement;
      btn.onclick = () => { row.remove(); onPick(r); };
      row.appendChild(btn);
    });
    msgsEl.appendChild(row); scrollDown();
  }

  function showTyping(): HTMLElement {
    const t = el('div', 'cm-typing', '<span></span><span></span><span></span>');
    msgsEl.appendChild(t); scrollDown();
    return t;
  }

  // ---- session / Firestore plumbing ----
  let sid = '';
  try { sid = window.localStorage.getItem('cm_widget_sid') || ''; } catch { /* ignore */ }
  if (!sid) {
    sid = 's' + Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
    try { window.localStorage.setItem('cm_widget_sid', sid); } catch { /* ignore */ }
  }
  const convoId = `${CONVO_PREFIX}${sid}`;
  const convoRef = doc(db, 'workspaces', workspaceId, 'conversations', convoId);
  const messagesRef = collection(db, 'workspaces', workspaceId, 'conversations', convoId, 'messages');
  const seenOutbound = new Set<string>();
  const seenClientIds = new Set<string>();

  let visitorName = '';
  let visitorEmail = '';
  let visitorPhone = '';
  let leadCaptured = false;
  let botPaused = false; // an agent took over
  let convoStarted = false;

  const bot = cfg.publishedFlow ? createSessionFromBotMap(cfg.publishedFlow) : null;
  const botSession: SupportBotSession | null = bot;

  async function upsertConvo(patch: Record<string, any>) {
    try {
      await setDoc(convoRef, {
        channel: 'web',
        widgetId: cfg.id,
        visitorSessionId: sid,
        lastMessageAt: Date.now(),
        updatedAt: new Date().toISOString(),
        ...patch,
      }, { merge: true });
    } catch (e) { console.warn('[ChatMize widget] convo upsert failed:', e); }
  }

  async function sendVisitorMessage(text: string, payload?: string) {
    const clientId = 'c' + Math.random().toString(36).slice(2, 10);
    seenClientIds.add(clientId);
    addMsg(text, 'user');
    try {
      await addDoc(messagesRef, {
        text,
        payload: payload || null,
        direction: 'inbound',
        channel: 'web',
        senderId: sid,
        senderRole: 'visitor',
        visitorName: visitorName || null,
        clientId,
        timestampMs: Date.now(),
        createdAt: new Date().toISOString(),
      });
      await upsertConvo({ lastMessageText: text });
    } catch (e) { console.warn('[ChatMize widget] send failed:', e); }
  }

  function runBotTurn(result: ReturnType<SupportBotSession['handleText']>) {
    const typing = showTyping();
    window.setTimeout(() => {
      typing.remove();
      result.texts.forEach((t) => addMsg(t, 'bot'));
      if (result.quickReplies.length > 0) {
        addQuickReplies(result.quickReplies, (r) => {
          if (!botSession || botPaused) return;
          sendVisitorMessage(r.label, r.payload);
          window.setTimeout(() => runBotTurn(botSession.handlePayload(r.payload, r.label)), 500);
        });
      }
      if (result.handoffToAgent) botPaused = false; // bot stays available; agent messages pause it on arrival
    }, 700);
  }

  function ensureBotStarted() {
    if (convoStarted) return;
    convoStarted = true;
    upsertConvo({ visitorName: visitorName || null, visitorEmail: visitorEmail || null });
    addMsg(cfg.welcomeMessage, 'bot');
    if (botSession && botSession.hasFlow() && !botPaused) {
      window.setTimeout(() => runBotTurn(botSession.start()), 900);
    } else if (cfg.quickReplies.length > 0) {
      window.setTimeout(() => {
        addQuickReplies(cfg.quickReplies.map((q) => ({ label: q.label, payload: q.payload })), (r) => {
          if (botSession && !botPaused) {
            sendVisitorMessage(r.label, r.payload);
            window.setTimeout(() => runBotTurn(botSession.handlePayload(r.payload, r.label)), 500);
          } else {
            sendVisitorMessage(r.label, r.payload);
          }
        });
      }, 900);
    }
  }

  // Realtime: agent/bot replies land here.
  onSnapshot(query(messagesRef, orderBy('timestampMs', 'asc')), (snap) => {
    snap.docChanges().forEach((ch) => {
      if (ch.type !== 'added') return;
      const d = ch.doc.data() as Record<string, any>;
      if (d.clientId && seenClientIds.has(d.clientId)) return; // our own echo
      if (d.direction === 'outbound') {
        if (seenOutbound.has(ch.doc.id)) return;
        seenOutbound.add(ch.doc.id);
        if (d.text) addMsg(String(d.text), 'bot');
        if (d.senderRole === 'agent') botPaused = true; // human took over
        if (Array.isArray(d.quickReplies) && d.quickReplies.length > 0) {
          addQuickReplies(d.quickReplies.map((q: any) => ({ label: String(q.label || q), payload: String(q.payload || q.label || q) })), (r) => {
            sendVisitorMessage(r.label, r.payload);
          });
        }
      }
    });
  }, (err) => console.warn('[ChatMize widget] listen failed:', err));

  // ---- lead capture ----
  function needsLead(): boolean {
    if (leadCaptured) return false;
    return cfg.requireNameCapture || cfg.requireEmailCapture || cfg.requirePhoneCapture;
  }

  function renderLeadForm() {
    leadEl.style.display = 'flex';
    inputBar.style.display = 'none';
    leadEl.innerHTML = `<p>Before we start — how can we reach you?</p>`;
    const mk = (ph: string, type: string, key: string) => {
      const i = document.createElement('input');
      i.placeholder = ph; i.type = type; i.dataset.key = key;
      leadEl.appendChild(i);
      return i;
    };
    if (cfg.requireNameCapture) mk('Your name', 'text', 'name');
    if (cfg.requireEmailCapture) mk('Email address', 'email', 'email');
    if (cfg.requirePhoneCapture) mk('Phone (optional)', 'tel', 'phone');
    const btn = el('button', '', 'Start chatting') as HTMLButtonElement;
    btn.style.background = cfg.brandColor;
    btn.onclick = () => {
      const vals: Record<string, string> = {};
      leadEl.querySelectorAll('input').forEach((i) => { vals[(i as HTMLInputElement).dataset.key!] = (i as HTMLInputElement).value.trim(); });
      if (cfg.requireEmailCapture && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(vals.email || '')) {
        (leadEl.querySelector('[data-key="email"]') as HTMLInputElement)?.focus();
        return;
      }
      visitorName = vals.name || '';
      visitorEmail = vals.email || '';
      visitorPhone = vals.phone || '';
      leadCaptured = true;
      leadEl.style.display = 'none';
      inputBar.style.display = 'flex';
      upsertConvo({ visitorName: visitorName || null, visitorEmail: visitorEmail || null, visitorPhone: visitorPhone || null });
      ensureBotStarted();
    };
    leadEl.appendChild(btn);
  }

  // ---- open / close ----
  let opened = false;
  function openPanel() {
    panel.classList.add('cm-open');
    launcher.style.display = 'none';
    if (!opened) {
      opened = true;
      if (needsLead()) renderLeadForm();
      else ensureBotStarted();
    }
  }
  function closePanel() {
    panel.classList.remove('cm-open');
    launcher.style.display = 'flex';
  }
  launcher.onclick = openPanel;
  closeBtn.onclick = closePanel;

  function submitInput() {
    const text = inputEl.value.trim();
    if (!text) return;
    inputEl.value = '';
    if (!botSession || botPaused) {
      sendVisitorMessage(text);
      return;
    }
    sendVisitorMessage(text);
    window.setTimeout(() => runBotTurn(botSession.handleText(text)), 600);
  }
  sendBtn.onclick = submitInput;
  inputEl.addEventListener('keydown', (e) => { if (e.key === 'Enter') submitInput(); });

  // Auto-open once per page view when configured.
  if (cfg.autoOpenDelaySeconds > 0) {
    window.setTimeout(() => { if (!opened) openPanel(); }, cfg.autoOpenDelaySeconds * 1000);
  }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => boot().catch((e) => console.warn('[ChatMize widget]', e)));
} else {
  boot().catch((e) => console.warn('[ChatMize widget]', e));
}
