import { LogBuildEntryInput } from './buildCatalog';

/**
 * Backfill seed data for deploys 1 through 17 plus the headline features
 * that shipped in the September launch window. NOT auto run. Karl or a
 * Super Admin triggers it from the Build Catalog admin tab.
 *
 * Copy is dash free per Karl's rule.
 */
export const BUILD_CATALOG_SEED: LogBuildEntryInput[] = [
  {
    title: 'Knowledge Base builder',
    summary: 'Build a help center with articles, search, and video embeds right inside ChatMize.',
    buildDate: '2026-09-16',
    goLiveDate: '2026-09-17',
    deployCommit: '667e433',
    tags: ['support'],
  },
  {
    title: 'Waitlist capture, overlay SDK, and contest engine',
    summary: 'Waitlist capture pages, the website overlay SDK, and viral contests with leaderboards.',
    buildDate: '2026-09-16',
    goLiveDate: '2026-09-17',
    deployCommit: '1872e09',
    bundleName: 'assets/index-BQ4o3t58.js',
    tags: ['growth'],
  },
  {
    title: 'Gamification, MCP API, and SegMate importer',
    summary: 'Badges and AI credit rewards, the MCP API for outside tools, and the SegMate migration importer.',
    buildDate: '2026-09-17',
    goLiveDate: '2026-09-18',
    deployCommit: 'b20522c',
    bundleName: 'assets/index-CQqEF2lX.js',
    tags: ['platform'],
  },
  {
    title: 'Send.chat link cloaker',
    summary: 'Branded short links on send.chat with takeover pages and Messenger handoff.',
    buildDate: '2026-09-17',
    goLiveDate: '2026-09-18',
    deployCommit: '406de68',
    tags: ['growth', 'platform'],
  },
  {
    title: 'QR builder',
    summary: 'Generate QR codes for growth links without leaving the app.',
    buildDate: '2026-09-17',
    goLiveDate: '2026-09-18',
    deployCommit: '9d268f6',
    tags: ['growth'],
  },
  {
    title: 'BotMaps video and audio upload',
    summary: 'Upload video and audio straight into BotMaps message steps.',
    buildDate: '2026-09-18',
    goLiveDate: '2026-09-18',
    deployCommit: '6b7cb0f',
    tags: ['botmaps'],
  },
  {
    title: 'Media first BotMaps messages',
    summary: 'Images, video, and audio now send before text. Media only messages work, files up to 25 MB.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '239e533',
    bundleName: 'assets/index-RkzVhWHe.js',
    tags: ['botmaps'],
  },
  {
    title: 'Meta compliant quick replies',
    summary: 'Quick replies cap at 13, titles at 20 characters, and they always ride on text first per Meta rules.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '841aefb',
    bundleName: 'assets/index-DI5MEqkU.js',
    tags: ['botmaps'],
  },
  {
    title: 'Contact capture and form autofill',
    summary: 'BotMaps can capture phone and email into contact fields, with browser autofill on growth tool forms.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '087e930',
    bundleName: 'assets/index-B7iu8E5v.js',
    tags: ['botmaps', 'growth'],
  },
  {
    title: 'BotMaps variables and webhooks',
    summary: 'Saved variables, contact fields, template tags, webhook POST steps, and MCP custom variable tools.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: 'bfe29d8',
    bundleName: 'assets/index-CRG0ZUar.js',
    tags: ['botmaps', 'integrations'],
  },
  {
    title: 'Google Sheets integration',
    summary: 'Connect a Google Sheet, list tabs and headers, append rows, and look up values from BotMaps.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '3970528',
    tags: ['integrations'],
  },
  {
    title: 'BigMarker integration',
    summary: 'Connect BigMarker, list webinars, register contacts, and sync attendance into contact tags.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '64fa604',
    tags: ['integrations'],
  },
  {
    title: 'Modular plan builder',
    summary: 'Every feature is now a module. Plans are composed from modules in the Super Admin plan composer.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '4343d83',
    bundleName: 'assets/index-Bun66_jI.js',
    tags: ['billing', 'platform'],
  },
  {
    title: 'Shopify integration',
    summary: 'Connect a Shopify store. Abandoned cart recovery, order updates, and post purchase flows in BotMaps.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '5dd453d',
    bundleName: 'assets/index-AlgvbE3x.js',
    tags: ['integrations'],
  },
  {
    title: 'Chatbot analytics dashboard',
    summary: 'Flow funnels, message stats, subscriber growth, broadcast reports, and attributed revenue in one dashboard.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '297055e',
    bundleName: 'assets/index-C-So7e1S.js',
    tags: ['analytics'],
  },
  {
    title: 'Survey builder',
    summary: 'Build surveys with rating, NPS, and choice questions. Embed in popups and slide ins or share by link.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: 'b85e148',
    bundleName: 'assets/index-DQMwVLnV.js',
    tags: ['growth'],
  },
  {
    title: 'Native bookings app',
    summary: 'ChatMize own booking system built in house. Availability, buffers, reminders, and BotMaps booking triggers.',
    buildDate: '2026-09-19',
    goLiveDate: '2026-09-19',
    deployCommit: '0a06ea5',
    bundleName: 'assets/index-BeI6_fkn.js',
    tags: ['growth', 'platform'],
  },
];
